In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
df= pd.read_excel(r'C:\Users\User\Downloads\anova_lab_data.xlsx')
df

   Power   Etching Rate
0   160 W          5.43
1   180 W          6.24
2   200 W          8.79
3   160 W          5.71
4   180 W          6.71
5   200 W          9.20
6   160 W          6.22
7   180 W          5.98
8   200 W          7.90
9   160 W          6.01
10  180 W          5.66
11  200 W          8.15
12  160 W          5.59
13  180 W          6.60
14  200 W          7.55

In [7]:
df.columns

Index(['Power ', 'Etching Rate'], dtype='object')

In [11]:
df.columns = df.columns.str.replace(' ', '').str.lower().str.replace('etchingrate', 'etching_rate')   #standarize columns name
df

    power  etching_rate
0   160 W          5.43
1   180 W          6.24
2   200 W          8.79
3   160 W          5.71
4   180 W          6.71
5   200 W          9.20
6   160 W          6.22
7   180 W          5.98
8   200 W          7.90
9   160 W          6.01
10  180 W          5.66
11  200 W          8.15
12  160 W          5.59
13  180 W          6.60
14  200 W          7.55

In [12]:
df.power = df.power.apply(lambda x: x.replace(' W', '') if x.endswith('W') else x)
df.power.unique()

array(['160', '180', '200'], dtype=object)

In [13]:
df

   power  etching_rate
0    160          5.43
1    180          6.24
2    200          8.79
3    160          5.71
4    180          6.71
5    200          9.20
6    160          6.22
7    180          5.98
8    200          7.90
9    160          6.01
10   180          5.66
11   200          8.15
12   160          5.59
13   180          6.60
14   200          7.55

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   power         15 non-null     object
 1   etching_rate  15 non-null     float64
dtypes: float64(1), object(1)
memory usage: 372.0+ bytes

In [15]:
df.power = df.power.astype(int)

#State the null hypothesis and the alternate hypothesis

    H0: m0 = m1 = m2 ... = mn  --> All the mean etching rates are equal for different levels of power

    H1: At least one of the mean for a different level of power is different to the other mean

Level of significance

    The level of significance is 0.05

    Confidence level: 95%

#What are the degrees of freedom of model, error terms, and total DoF

In [18]:
npower = df.power.unique()
print('Total samples in the dataset: ', len(npower))

print('Degrees of freedom between samples: ', len(npower)-1)

n = df.shape[0] 
print('Number of observations in the dataset: ', n)

print('Degrees of freedom of the model: ', n-1)

Total samples in the dataset:  3
Degrees of freedom between samples:  2
Number of observations in the dataset:  15
Degrees of freedom of the model:  14

In [20]:
df.pivot(columns='power').describe().T   #checking the mean of the samples

                    count   mean       std   min   25%   50%   75%   max
             power
etching_rate 160      5.0  5.792  0.319875  5.43  5.59  5.71  6.01  6.22
             180      5.0  6.238  0.434304  5.66  5.98  6.24  6.60  6.71
             200      5.0  8.318  0.669604  7.55  7.90  8.15  8.79  9.20

##Part 2

Use Python to conduct ANOVA. What conclusions can you draw from the experiment and why?

In [22]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('etching_rate ~ power ',data=df).fit()
sm.stats.anova_lm(model)

            df     sum_sq    mean_sq          F    PR(>F)
power      1.0  15.951690  15.951690  40.016178  0.000026
Residual  13.0   5.182203   0.398631        NaN       NaN

The P value 0.000008 is lower than our selected level of significance of 0.05, so we reject null hypothesis. This means that levels of power impact the etching rate, but we can't tell which one yet.